metadata:
  max_epochs: 200
  data_path: "../../data/raw/"
  accelerator: "cpu"
  data_size: 10

simulations:
# FORECAST SIZE = 2
## NO HOP
  - tags: ["zero hop", "forecast=2", "spatio-gru"]
    name: "spatio-temporal-GRU"
    description: "Learning process of the spatio temporal GRU model with no communication"
    module: &sequential "project.model.sequential"
    class_name: &stgru "SpatialPlusTemporal"
    args: &base
      - &input_feature 1
      - &simple_forecast 2
      - &hidden_feature 32
      - 16
